#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit


################################################################################
#
# Run the root tests
#
################################################################################

./grunt-tc clean validate:common test:unit compile assetmonitor:common
./sbt-tc compile test

echo "Done testing."
